In [71]:
%config InteractiveShell.ast_node_interactivity = 'all'

In [5]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

import matplotlib.pyplot as plt
import mlxtend.frequent_patterns
import mlxtend.preprocessing
import numpy

## Segmentaci√≥n de clientes

## Canasta de mercado

Se busca con esta herramientas encontrar aquellos productos que se venden juntos en los distintos locales

In [10]:
data = pd.read_csv("./dataset/coffee-shop-sales-revenue.csv", delimiter='|')
data['datetime'] = pd.to_datetime(data['transaction_date'] + ' ' + data['transaction_time'])
data.head()

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,datetime
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.0,Coffee,Gourmet brewed coffee,Ethiopia Rg,2023-01-01 07:06:11
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,2023-01-01 07:08:56
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.5,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,2023-01-01 07:14:04
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.0,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2023-01-01 07:20:24
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.1,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,2023-01-01 07:22:41

In [11]:
# Obtengo las ubicaciones de los locales
locales = data.drop_duplicates(subset=['store_location'])['store_location']
print(locales)

0      Lower Manhattan
17      Hell's Kitchen
105            Astoria
Name: store_location, dtype: object

In [14]:
# Extraigo las transacciones por locales
datos_por_local = []
for local in locales:
    ventas = data[data['store_location'] == local][['datetime', 'product_type']]
    datos_por_local.append(ventas)

In [24]:
# Extraigo los tipos de productos que se vendieron en cada local
tmpVentas = []
productos = []
for x in range(len(datos_por_local)):
    tmpVentas.append(datos_por_local[x])
    productos.append(pd.DataFrame(datos_por_local[0]).drop_duplicates('product_type')['product_type'].tolist())    
    productos[x].insert(0, 'datetime')

In [35]:
# Convierto los productos en columnas
MBA_data = []
for x in range(len(productos)):
    MBA_data.append(pd.DataFrame([productos[x]]))
    MBA_data[x].columns = productos[x]

In [36]:
# NO EJECUTAR A MENOS QUE SEA NECESARIO
# Construyo la matriz en base a productos comprados por fecha

for x in range(len(MBA_data)): 
    for index, row in tmpVentas[x].iterrows():
        fila = []
        fila.append(row['datetime'])
        #print(row['product_type'])
        for col in MBA_data[x].iloc[:, 1:]:
            if row['product_type'] == col:
                fila.append(1)
            else:
                fila.append(0)
        MBA_data[x].loc[len(MBA_data[x])] = fila
    MBA_data[x] = MBA_data[x].iloc[1:].reset_index(drop=True)

In [41]:
# Agrupamos las columnas que tienen la misma fecha
MBA_data_grp = []
for x in range(len(MBA_data)):
    MBA_data_grp.append(MBA_data[x].groupby('datetime').sum().reset_index())
    MBA_data_grp[x] = MBA_data_grp[x].drop(columns=['datetime'])
    MBA_data_grp[x] = MBA_data_grp[x].map(lambda x: True if x >= 1 else False)

In [46]:
# Realizamos el an√°lisis
frequent_itemsets = []
rules = []
for x in range(len(MBA_data_grp)):
    frequent_itemsets.append(apriori(MBA_data_grp[x], min_support=0.001, use_colnames=True))
    rules.append(association_rules(frequent_itemsets[x], metric="lift"))
    #rules.sort_values(['support', 'confidence', 'lift'], axis = 0, ascending = False).head(10)

In [74]:
# Mostramos los valores obtenidos
for x in range(len(rules)):
    print("--------------------------------------------------------------------------------------------------------------------------------------------")
    print(f"Localidad: {locales.iloc[x]}")
    rules[x].sort_values(['support', 'confidence', 'lift'], axis = 0, ascending = False).head(10)

--------------------------------------------------------------------------------------------------------------------------------------------
Localidad: Lower Manhattan

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
47,(Regular syrup),(Barista Espresso),0.058706,0.148631,0.058622,0.998567,6.718418,0.049897,593.971624,0.904240
46,(Barista Espresso),(Regular syrup),0.148631,0.058706,0.058622,0.394414,6.718418,0.049897,1.554352,0.999749
51,(Sugar free syrup),(Barista Espresso),0.023253,0.148631,0.023253,1.000000,6.728062,0.019796,inf,0.871637
50,(Barista Espresso),(Sugar free syrup),0.148631,0.023253,0.023253,0.156445,6.728062,0.019796,1.157894,1.000000
25,(Scone),(Barista Espresso),0.097330,0.148631,0.021570,0.221614,1.491032,0.007103,1.093761,0.364832
24,(Barista Espresso),(Scone),0.148631,0.097330,0.021570,0.145122,1.491032,0.007103,1.055905,0.386816
6,(Scone),(Brewed Chai tea),0.097330,0.142040,0.013267,0.136311,0.959670,-0.000558,0.993367,-0.044485
7,(Brewed Chai tea),(Scone),0.142040,0.097330,0.013267,0.093404,0.959670,-0.000558,0.995670,-0.046695
1,(Scone),(Gourmet brewed coffee),0.097330,0.146331,0.012285,0.126225,0.862597,-0.001957,0.976989,-0.149997
0,(Gourmet brewed coffee),(Scone),0.146331,0.097330,0.012285,0.083956,0.862597,-0.001957,0.985401,-0.157253

--------------------------------------------------------------------------------------------------------------------------------------------
Localidad: Hell's Kitchen

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
33,(Regular syrup),(Barista Espresso),0.043704,0.151456,0.043407,0.993213,6.557765,0.036788,125.018820,0.886241
32,(Barista Espresso),(Regular syrup),0.151456,0.043704,0.043407,0.286600,6.557765,0.036788,1.340477,0.998780
15,(Scone),(Barista Espresso),0.084590,0.151456,0.019207,0.227060,1.499183,0.006395,1.097814,0.363739
14,(Barista Espresso),(Scone),0.151456,0.084590,0.019207,0.126816,1.499183,0.006395,1.048358,0.392402
35,(Sugar free syrup),(Barista Espresso),0.014881,0.151456,0.014881,1.000000,6.602579,0.012627,inf,0.861362
34,(Barista Espresso),(Sugar free syrup),0.151456,0.014881,0.014881,0.098254,6.602579,0.012627,1.092457,1.000000
1,(Scone),(Gourmet brewed coffee),0.084590,0.139294,0.010283,0.121566,0.872732,-0.001500,0.979819,-0.137412
0,(Gourmet brewed coffee),(Scone),0.139294,0.084590,0.010283,0.073824,0.872732,-0.001500,0.988376,-0.144881
20,(Scone),(Brewed herbal tea),0.084590,0.091511,0.006773,0.080070,0.874975,-0.000968,0.987563,-0.135018
21,(Brewed herbal tea),(Scone),0.091511,0.084590,0.006773,0.074014,0.874975,-0.000968,0.988579,-0.135907

--------------------------------------------------------------------------------------------------------------------------------------------
Localidad: Astoria

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
41,(Regular syrup),(Barista Espresso),0.027259,0.119531,0.027013,0.990983,8.290592,0.023755,97.644010,0.904024
40,(Barista Espresso),(Regular syrup),0.119531,0.027259,0.027013,0.225992,8.290592,0.023755,1.256759,0.998765
6,(Scone),(Brewed Chai tea),0.078483,0.153893,0.012290,0.156593,1.017539,0.000212,1.003200,0.018705
7,(Brewed Chai tea),(Scone),0.153893,0.078483,0.012290,0.079859,1.017539,0.000212,1.001496,0.020372
1,(Scone),(Gourmet brewed coffee),0.078483,0.148658,0.010840,0.138115,0.929077,-0.000827,0.987767,-0.076502
0,(Gourmet brewed coffee),(Scone),0.148658,0.078483,0.010840,0.072917,0.929077,-0.000827,0.993996,-0.082289
43,(Sugar free syrup),(Barista Espresso),0.009316,0.119531,0.009045,0.970976,8.123216,0.007932,30.336159,0.885142
42,(Barista Espresso),(Sugar free syrup),0.119531,0.009316,0.009045,0.075673,8.123216,0.007932,1.071790,0.995942
12,(Scone),(Hot chocolate),0.078483,0.105447,0.009021,0.114939,1.090018,0.000745,1.010725,0.089617
13,(Hot chocolate),(Scone),0.105447,0.078483,0.009021,0.085548,1.090018,0.000745,1.007726,0.092318

## Arbol de decisi√≥n